config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/' ,to:'root#root' ,as: :root


  resources:ideas do 
    resources :reviews, only: [:create, :destroy]
end

resources:users ,only: [:new, :create]


resource:session,only: [:new, :create, :destroy]
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
      if user.is_admin?
       can :manage, :all
      end
     #else
       # can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    alias_action :create, :read, :update, :destroy, to: :crud

    can(:crud, Idea) do |idea|
      Idea.user == user 
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord

    belongs_to :user
    
    has_many:reviews, dependent: :destroy

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :idea
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    has_many :ideas, dependent: :nullify
    has_many :reviews, dependent: :nullify

    VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: true, format: VALID_EMAIL_REGEX
    scope(:created_after, -> (date) { where("created_at < ?", "#{date}") })
    scope(:search, -> (query) { where("first_name ILIKE ? OR last_name ILIKE ? OR email ILIKE ?", "%#{query}%", "%#{query}%", "%#{query}%") })

    def full_name 
        "#{first_name} #{last_name}".strip
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def current_user
        if session[:user_id].present?
            @current_user ||= User.find session[:user_id] 
        end
    end
    helper_method :current_user 

    def user_signed_in? 
        current_user.present?
    end

    helper_method :user_signed_in?

    def authenticate_user! 
        unless user_signed_in? 
            flash[:danger] = "You need to be signed in first!"
            redirect_to new_session_path
        end
    end
    
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
    before_action :find_idea, only: [:show, :edit, :update, :destroy]
    # before_action is a controller hook provided by rails
    # 1 - it accepts a method name
    # 2 - options hash
    before_action :authenticate_user!, except: [:index, :show]
    # will call authenticate_user! before every method except :index, and :show
    before_action :authorize!, only: [:edit, :update, :destroy]
    
    def index
        #if params[:tag]
          #  @tag = Tag.find_or_initialize_by(name: params[:tag])
          #  @questions = @tag.questions.all_with_answer_counts.order('updated_at DESC')
        #else
            @ideas = Idea.all
       # end
    end

    def new
        @idea = Idea.new
    end
    def create

        @idea = Idea.new idea_params 
        @idea.user = current_user
        if @idea.save
            flash[:notice] = 'Idea created successfully'
            # if question is saved successfully, redirect to question show page with that question
            redirect_to idea_path(@idea)
        else 
            # render views/questions/new.html.erb
            render :new 
        end
    end

    def show
       
        @review = Review.new
       

        @reviews = @idea.reviews.order(created_at: :desc)

        #@like = @question.likes.find_by(user: current_user)
    end

    def index
        #if params[:tag]
          #  @tag = Tag.find_or_initialize_by(name: params[:tag])
          #  @questions = @tag.questions.all_with_answer_counts.order('updated_at DESC')
        #else
            @ideas = Idea.all
       # end
    end

    def edit
    end 

    def update
       
        if @idea.update idea_params
            redirect_to idea_path(@idea)
        else
            render :edit
        end

    end

    def destroy 
        flash[:notice] = "Idea destroyed!"
        @idea.destroy 
        redirect_to ideas_path
    end

    #def liked 
        # all the question that this particular logged in user has liked
       # @questions = current_user.liked_questions.all_with_answer_counts.order(created_at: :desc)
   # end

    private 

    def idea_params
         
        params.require(:idea).permit(:title, :description)
    end

    def find_idea
        # get the Question with the id that's requested
        @idea = Idea.find params[:id]
    end

    def authorize! 
       redirect_to root_path, alert: 'Not Authorized' unless can?(:crud, @idea)
    end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def create 
        #byebug
        @idea = Idea.find params[:idea_id]
        
        @review = Review.new review_params
        @review.user=current_user
        @review.idea = @idea 
      
        if @review.save
    
            redirect_to idea_path(@idea)
        else 

            @ideas = @idea.reviews.order(created_at: :desc)
            render 'ideas/show'
        end
    end

    def destroy
       
        @review = Review.find params[:id]
       
            @review.destroy 
            redirect_to idea_path(@review.idea)
    end

    private

    def review_params 
        params.require(:review).permit(:body)
    end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
    def root 
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
  
    def create
      user = User.find_by_email params[:email]
      if user&.authenticate params[:password]
        
        session[:user_id] = user.id 
        redirect_to root_path, notice: "Signed in!"
      else
        flash[:alert] = "Wrong email or password"
        render :new 
      end
    end
  
    def destroy
      session[:user_id] = nil 
      redirect_to root_path, notice: 'Logged Out!'
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new 
        @user = User.new
    end

    def create 
        @user = User.new user_params
        if @user.save 
            
            flash[:notice] = "Thank you for signing up!"
            redirect_to ideas_path
        else 
            flash[:warning] = "Unable to create user"
            render :new 
        end
    end

    def edit

        @user=User.find params[:id]
    end
    def update
       
       

    end

    private 

    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/_form.html.erb
<% if @idea.errors.present? %>
    <p>
        <%= @idea.errors.full_messages.join(', ') %>
    </p>
<% end %>

<%= form_with  model: @idea, local: true do |f| %>
    
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control', cols: 50, rows: 5 %>
    </div>
  
    <%= f.submit %>
<% end %>

app/views/ideas/_list.html.erb
<div class="row">
    <div class="=col-2">
    </div>

    <div class="col-10">
    <% @ideas.each do |idea| %>
        <div>
            <h3><%= link_to idea.title, idea_path(idea) %></h3>
            <h3><%= idea.description %></h3>   
        </div>
    <% end %>
    </div>
</div>

app/views/ideas/edit.html.erb
<h1>Idea Edit Page</h1>
<%= render "form" %>

app/views/ideas/index.html.erb
<h1>All Ideas</h1>
<%= render 'list'%>

app/views/ideas/new.html.erb
<h1>Idea New Page</h1>
<%= render "form" %>

app/views/ideas/show.html.erb
<div class="shadow-sm p-3 mb-5 bg-white rounded overflow-wrap">
    <h1>
        <span class="badge badge-pill badge-info">
            <%= @idea.title %>
        </span>
    </h1>
    <p class="shadow-none p-3 mb-5 bg-light rounded"><%= @idea.description %></p>
    <div>
    <%= link_to "Edit", edit_idea_path(@idea), class: 'btn btn-info' %>
    <%= link_to "Delete", idea_path(@idea), 
        method: :delete, 
        class: 'btn btn-danger',
        data: { confirm: "Are you sure?" } 
    %>
</div>
<%= form_with(model: [@idea, @review], local: true) do |f| %>
    <% if @review.errors.any? %>
        <ul>
            <% @review.errors.full_messages.each do |msg| %>
                <li class="text-danger"><%= msg %></li>
            <% end %>
        </ul>
    <% end %>

    <div class="form-group">
       <%= f.text_area(
           :body,
           cols: 50,
           rows: 5,
           placeholder: "What are your thoughts?",
           class: "form-control"
       )%>
    </div>

    <%= f.submit "Review", class: "btn-primary" %>

<% end %>



<ul class="list-group answer-list">
    <% @reviews.each do |review| %>
        <li class="list-group-item">
            <p>
                <%= review.body %>
            </p>
            <small>
            
             <%= link_to(
                 "Delete",
                 idea_review_path(@idea, review),
                 method: :delete,
                 data: {
                     confirm: "Are you sure?"
                 },
                 class: "btn btn-danger btn-sm"
             )%>
            </small>

            </p>
        </li>
    <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaWithRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
  <% flash.each do |type, message| %>
    <div class="bg-<%= type %> p-3 rounded mb-2 shadow-sm">
      <%= message %>
    </div>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/root/root.html.erb
<h1> Welcome to Ideas with Rails Page </h1>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
<a class="navbar-brand" href="#">Blog On Rails</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
    <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarNav">
<ul class="navbar-nav mr-auto">

</ul>
<ul class="navbar-nav navigation-links">
    <li class="nav-item nav-links">
        <%= link_to 'Home', root_path %>
    </li>
    <% if user_signed_in? %>
    <li class="nav-item nav-links">
        <%= link_to 'New Idea', new_idea_path %>
    </li>
    <li class="nav-item nav-links">
        <%= link_to 'All Ideas', ideas_path %>
    </li>
  
    <li class="nav-item nav-links">
        <a><%= current_user.full_name %></a>
    </li>
    <li class="nav-item nav-links">
        <%= link_to "Log Out", session_path, method: :delete, class: 'btn btn-danger' %>
    </li>
<% else %>
    <li class="nav-item nav-links">
      <%= link_to "Sign In", new_session_path %>
    </li>
    <li class="nav-item nav-links">
    <%= link_to "Sign Up", new_user_path %>
  </li>
<% end %>
</ul>
</div>
</nav>
<div class="container">

app/views/users/edit.html.erb
<% if @post.errors.present? %>
    <p>
        <%= @post.errors.full_messages.join(', ') %>
    </p>
<% end %>

<%= form_with model: @user, local: true do |f| %>
    <div>
        <%= f.label :fullname %>
        <%= f.text_field :fullname %>
      
        <%= f.label :email %>
        <%= f.text_field :email %>
    </div>

        <%= f.submit %>
    </div>
<% end %>

app/views/users/new.html.erb
<h1>User New Page</h1>
<% if @user.errors.present? %>
    <p>
        <%= @user.errors.full_messages.join(', ') %>
    </p>
<% end %>

<div class="shadow-sm p-3 mb-5 bg-white rounded">
    <%= form_with model: @user, local: true do |f| %>
        <div class="form-group">
            <%= f.label :first_name %>
            <%= f.text_field :first_name, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :last_name %>
            <%= f.text_field :last_name, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>

        <%= f.submit 'Create User', class: 'btn btn-primary' %>
    <% end %>